

const assetsPath = './assets';

export const randomContent = [
  {
    title: 'Sons Of The Forest',
    category: 'Horror',
    txt: 'Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/horror-card1.jpg`,
    video: `${assetsPath}/media/example-video.webm`,
    videoType: 'video/webm',
    newPrice: '97 $',
    oldPrice: '295 $',
    likes: '233',

  },
  {
    title: 'Project Zomboid',
    category: 'Horror',
    txt: 'Project Zomboid is the ultimate in zombie survival. Alone or in MP: you loot, build, craft, fight, farm and fish in a struggle to survive. A hardcore RPG skillset, a vast map, massively customisable sandbox and a cute tutorial raccoon await the unwary. So how will you die? All it takes is a bite.. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/horror-card2.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '54 $',
    oldPrice: '105 $',
    likes: '186',
  },
  {
    title: 'Black Myth: Wukong',
    category: 'Horror',
    txt: 'Black Myth: Wukong is an action movie based on Chinese mythology. As the Chosen One, you will embark on an adventure full of challenges and wonders, in which you will have to lift the veil of secrecy over the Great One. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/horror-card3.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '27 $',
    oldPrice: '665 $',
    likes: '537',
  },

  {
    title: 'Naraka: Blandepoin',
    category: 'Action',
    txt: 'NARAKA: BLADEPOINT is a 60-player battle royale game inspired by the myths and legends of the Far East. The game combines various types of martial arts, a vast arsenal of melee and ranged weapons, as well as many characters with incredible. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/action-card1.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '27 $',
    oldPrice: '665 $',
    likes: '27',
  },
  {
    title: 'Pubg: Battlegrounds',
    category: 'Action',
    txt: 'With over 175 awards and 250 top ratings from gaming publications, RDR2 is the epic story of outlaw Arthur Morgan and the Van der Linde gang as they flee the law across America at the dawn of the modern era. Includes free access to co-op play in the world of Red Dead Online. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/action-card2.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '17 $',
    oldPrice: '565 $',
    likes: '274',
  },
  {

    title: 'Red Dead Redemption 2',
    category: 'Action',
    txt: 'Land in strategically important places, get weapons and supplies and try to survive and be the last team left on one of the many battlefields. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/action-card3.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '17 $',
    oldPrice: '165 $',
    likes: '227',
  },
  {

    title: 'Valheim',
    category: 'Survarial',
    txt: 'Apex Legends is an award-winning free-to-play hero shooter from Respawn Entertainment. Master the ins and outs of playing as a growing number of legendary characters and use their powerful skills to inform your squads strategy. This is new. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/survarial-card1.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '247 $',
    oldPrice: '165 $',
    likes: '127',
  },
  {
    title: 'Dont Starve Together',
    category: 'Survarial',
    txt: 'Fight, Farm, Build and Explore Together in the standalone multiplayer expansion to the uncompromising wilderness survival game, Dont Starve. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/survarial-card2.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '27 $',
    oldPrice: '625 $',
    likes: '27',
  },
  {
    title: 'Apex Legends',
    category: 'Survarial',
    txt: 'A survival game in which you explore a vast fantasy world steeped in Norse mythology and Viking culture. Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.',
    image: `${assetsPath}/images/survarial-card3.jpg`,
    video: ``,
    videoType: 'video/webm',
    newPrice: '27 $',
    oldPrice: '435 $',
    likes: '17',
  },
];

